version: '3.8'

services:
  backend:
    build: 
      context: ../
    command: uvicorn core.app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../core:/app/core
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"

volumes:
  postgres_data: